ALG: 'dynaq'

# EXPERIMENT PARAMS
NUM_SEEDS: 1
SEED: 1
LANDMARK_FEATURES: False

# logggin
MAX_EPISODE_LOG_LEN: 40


# RUN PARAMS
TOTAL_TIMESTEPS: 70_000_000
NUM_ENVS: 32
EVAL_STEPS: 100
EVAL_EPISODES: 100
LEARNER_LOG_PERIOD: 500
#LEARNER_EXTRA_LOG_PERIOD: 5_000
LEARNER_EXTRA_LOG_PERIOD: 0
EVAL_LOG_PERIOD: 25
EVAL_LOG_PERIOD_ACTOR: 0
#GRADIENT_LOG_PERIOD: 5_000
GRADIENT_LOG_PERIOD: 0

# NEURAL NET PARAMS
EMBED_HIDDEN_DIM: 64
NUM_MLP_LAYERS: 0
NUM_EMBED_LAYERS: 0
MLP_HIDDEN_DIM: 256
AGENT_RNN_DIM: 256
ACTIVATION: 'leaky_relu'
NUM_Q_LAYERS: 2
NUM_PRED_LAYERS: 2
Q_HIDDEN_DIM: 1024
QHEAD_TYPE: 'duelling'
SHARE_HEADS: False
OBS_INCLUDE_GOAL: true
SHARE_Q_FN: true

# ALGO PARAMS
BUFFER_SIZE: 50_000
TOTAL_BATCH_SIZE: 1280
BUFFER_BATCH_SIZE: 32
SAMPLE_LENGTH: null
LEARNING_STARTS: 10_000
TRAINING_INTERVAL: 5

# DYNA PARAMS
NUM_SIMULATIONS: 2
NUM_DYNA_SIMULATIONS: 1
NUM_OFFTASK_GOALS: 4
NUM_OFFTASK_SIMULATIONS: 1
INCLUDE_ACHIEVABLE: True
SIM_EPSILON_SETTING: 1 # range of epsilons
TERMINATE_OFFTASK: False
SUBTASK_COEFF: 2.0
WINDOW_SIZE: 1.
STEP_COST: 0.0

SIMULATION_LENGTH: 10
DYNA_COEFF: 1.0
ONLINE_COEFF: 1.0
STOP_DYNA_GRAD: False
TEMP_CONCENTRATION: .25
TEMP_RATE: .5
OFFTASK_SIMULATION: True
OFFTASK_COEFF: 1e-1


FIXED_EPSILON: 2 # range of epsilons
EPSILON_START: 1.0
EPSILON_FINISH: 0.1
EPSILON_ANNEAL_TIME: 5e5
MAX_GRAD_NORM: 80
TARGET_UPDATE_INTERVAL: 1_000
LR: 0.0003
LR_LINEAR_DECAY: FALSE
EPS_ADAM: 0.00001

GAMMA: 0.992
