ALG: 'qlearning'

# EXPERIMENT PARAMS
NUM_SEEDS: 1
SEED: 1

# logggin
MAX_EPISODE_LOG_LEN: 40


# RUN PARAMS
TOTAL_TIMESTEPS: 20_000_000
NUM_ENVS: 32
EVAL_STEPS: 100
EVAL_EPISODES: 100
LEARNER_LOG_PERIOD: 500
LEARNER_EXTRA_LOG_PERIOD: 5_000
EVAL_LOG_PERIOD: 25
EVAL_LOG_PERIOD_ACTOR: 0
GRADIENT_LOG_PERIOD: 5_000

# NEURAL NET PARAMS
EMBED_HIDDEN_DIM: 64
NUM_MLP_LAYERS: 0
NUM_EMBED_LAYERS: 0
MLP_HIDDEN_DIM: 256
AGENT_RNN_DIM: 256
ACTIVATION: 'leaky_relu'
NUM_Q_LAYERS: 2

# ALGO PARAMS
BUFFER_SIZE: 50_000
BUFFER_BATCH_SIZE: 32
SAMPLE_LENGTH: 40
LEARNING_STARTS: 10_000
TRAINING_INTERVAL: 5

FIXED_EPSILON: 2 # range of epsilons
EPSILON_START: 1.0
EPSILON_FINISH: 0.1
EPSILON_ANNEAL_TIME: 5e5
MAX_GRAD_NORM: 80
TARGET_UPDATE_INTERVAL: 1_000
LR: 0.001
LR_LINEAR_DECAY: FALSE
EPS_ADAM: 0.00001

GAMMA: 0.99
