name: preplay-ai
channels:
  - conda-forge
dependencies:
  - pip:
    - wandb
    - ipdb
    - tqdm
    - rlax==0.1.6
    - matplotlib
    - numpy==1.26.4
    - mctx==0.0.5
    - craftax
    - safetensors
    - ray[tune]==2.10.0
    - typing_extensions==4.11.0
    - optax==0.2.1
    - scipy==1.12.0
    - git+https://github.com/wcarvalho/JaxHouseMaze.git
    - jax[cuda12]
    - '-e libraries/jaxneurorl'
