defaults:
- _self_
- alg: ql.yaml
- rlenv: housemaze.yaml
- user: wilka.yaml
- debug: short.yaml

hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .

app:
  parallel: "none"  # none, slurm_wandb, slurm, wandb
  subprocess: false  # indicate if this run is a subprocess
  search_method: "grid"
  debug_sweep: false
  debug: false
  search: ""  # Specify the search term if needed
  wandb: true
  num_gpus: 1
  num_cpus: 12
  config_idx: 1  # which config to load, only used by vanilla slurm
  memory: 120000  # in MB
  time: "0-48:00:00"  # duration format for SLURM
  max_concurrent: 12
  account: "kempner_fellows"  # specify if there's a default account
  partition: "kempner"  # default SLURM partition
  settings_config: ""  # to be set by launcher.py
  PROJECT: null  # name of wandb project, note uppercase
  group: null  # name of wandb project
  base_path: null  # name of wandb project
