# WANDB PARAMS
PROJECT: "craftax"
ENV_NAME: "craftax-gen"
ENV: "craftax-gen"
TOTAL_TIMESTEPS: 10_000_000

OPTIMISTIC_RESET_RATIO: 16
USE_PRECONDITION: True

EVAL_STEPS: 1000
EVAL_EPISODES: 100  # 32 x (150,000)
EPSILON_ANNEAL_TIME: 5e5
FIXED_EPSILON: 0

TRAINING_INTERVAL: 1
LEARNING_STARTS: 0

MAX_PRIORITY_WEIGHT: 0.0
IMPORTANCE_SAMPLING_EXPONENT: 0.0
USE_BIAS: False
ACTIVATION: 'leaky_relu'
NUM_MLP_LAYERS: 1
MLP_HIDDEN_DIM: 512
NUM_Q_LAYERS: 3
NUM_AUX_LAYERS: 0
AGENT_RNN_DIM: 256


