# WANDB PARAMS
PROJECT: "craftax"
ENV_NAME: "craftax-gen"
ENV: "craftax-gen"
TOTAL_TIMESTEPS: 1_000_000

OPTIMISTIC_RESET_RATIO: 16  # reset every env?
USE_PRECONDITION: True

EVAL_STEPS: 100
EVAL_EPISODES: 10  # 32 x (1,000)
EPSILON_ANNEAL_TIME: 5e5
FIXED_EPSILON: 0
STEP_COST: 0.001

SIMULATION_LENGTH: 10
TRAINING_INTERVAL: 1
SIM_EPSILON_SETTING: 3
LEARNING_STARTS: 0

WINDOW_SIZE: 40
MAX_PRIORITY_WEIGHT: 0.0
IMPORTANCE_SAMPLING_EXPONENT: 0.0
USE_BIAS: False
ACTIVATION: 'relu'
NUM_MLP_LAYERS: 1
MLP_HIDDEN_DIM: 512
NUM_OFFTASK_GOALS: 6
NUM_Q_LAYERS: 1
NUM_AUX_LAYERS: 1
AGENT_RNN_DIM: 256