# WANDB PARAMS
PROJECT: "craftax"
ENV_NAME: "craftax-gen"
ENV: "craftax-gen"
TOTAL_TIMESTEPS: 10_000_000

OPTIMISTIC_RESET_RATIO: 16
USE_PRECONDITION: True

EVAL_STEPS: 100
EVAL_EPISODES: 10  # 32 x (1,000)
EPSILON_ANNEAL_TIME: 5e5
FIXED_EPSILON: 2
STEP_COST: 0.001

TRAINING_INTERVAL: 1
LEARNING_STARTS: 0
LR: 0.0003
AUX_COEFF: 1e-2

MAX_PRIORITY_WEIGHT: 0.9
IMPORTANCE_SAMPLING_EXPONENT: 0.6
USE_BIAS: False
ACTIVATION: 'leaky_relu'
NUM_MLP_LAYERS: 1
MLP_HIDDEN_DIM: 512
NUM_Q_LAYERS: 1
NUM_AUX_LAYERS: 0
AGENT_RNN_DIM: 256


