# WANDB PARAMS
PROJECT: "craftax"
ENV_NAME: "craftax-gen"
ENV: "craftax-gen"

TOTAL_TIMESTEPS: 1_000_000
EPSILON_ANNEAL_TIME: 5e5
OPTIMISTIC_RESET_RATIO: 1  # reset every env?
FIXED_EPSILON: 0

SIMULATION_LENGTH: 5
TRAINING_INTERVAL: 1
LEARNING_STARTS: 0


USE_BIAS: False
ACTIVATION: 'leaky_relu'
NUM_MLP_LAYERS: 0
MLP_HIDDEN_DIM: 512
NUM_Q_LAYERS: 3
AGENT_RNN_DIM: 512
