# WANDB PARAMS
PROJECT: "craftax"
ENV_NAME: "craftax-gen"
ENV: "craftax-gen"
TOTAL_TIMESTEPS: 1_000_000

OPTIMISTIC_RESET_RATIO: 1  # reset every env?
FIXED_EPSILON: 0
SIMULATION_LENGTH: 5
TRAINING_INTERVAL: 1
LEARNING_STARTS: 0