# WANDB PARAMS
PROJECT: "craftax"
ENV_NAME: "craftax-gen"
ENV: "craftax-gen"

USE_PRECONDITION: True

TOTAL_TIMESTEPS: 1_000_000
EVAL_STEPS: 1000
EVAL_EPISODES: 110  # 32 x (150,000)
EPSILON_ANNEAL_TIME: 5e5
OPTIMISTIC_RESET_RATIO: 1  # reset every env?
FIXED_EPSILON: 0

SIMULATION_LENGTH: 10
TRAINING_INTERVAL: 1
SIM_EPSILON_SETTING: 3
LEARNING_STARTS: 0

WINDOW_SIZE: 40
MAX_PRIORITY_WEIGHT: 0.0
IMPORTANCE_SAMPLING_EXPONENT: 0.0
USE_BIAS: False
ACTIVATION: 'relu'
NUM_MLP_LAYERS: 1
MLP_HIDDEN_DIM: 512
NUM_OFFTASK_GOALS: 5
NUM_Q_LAYERS: 1
NUM_AUX_LAYERS: 0
AGENT_RNN_DIM: 512


