# WANDB PARAMS
PROJECT: "craftax"
ENV_NAME: "craftax-gen"
ENV: "craftax-gen"
TOTAL_TIMESTEPS: 1_000_000

OPTIMISTIC_RESET_RATIO: 16  # reset every env?
USE_PRECONDITION: True

TEST_NUM_ENVS: 10_000
EVAL_STEPS: 100
EVAL_EPISODES: 10  # 32 x (1,000)
EVAL_LOG_PERIOD_ACTOR: 25
EPSILON_ANNEAL_TIME: 5e5
FIXED_EPSILON: 0
STEP_COST: 0

SIMULATION_LENGTH: 20
TRAINING_INTERVAL: 1
LEARNING_STARTS: 0


MAX_PRIORITY_WEIGHT: 0.0
IMPORTANCE_SAMPLING_EXPONENT: 0.0
USE_BIAS: True
ACTIVATION: 'relu'
NUM_MLP_LAYERS: 1
MLP_HIDDEN_DIM: 512

NUM_SIMULATIONS: 4  # Dyna
NUM_DYNA_SIMULATIONS: 1  # Preplay
NUM_OFFTASK_SIMULATIONS: 1  # Preplay
NUM_OFFTASK_GOALS: 3 # Preplay
NUM_Q_LAYERS: 1
NUM_AUX_LAYERS: 1
AGENT_RNN_DIM: 256
GAMMA: .99
