# WANDB PARAMS
PROJECT: "craftax"
ENV_NAME: "craftax-gen"
ENV: "craftax-gen"
TOTAL_TIMESTEPS: 10_000_000

OPTIMISTIC_RESET_RATIO: 16
USE_PRECONDITION: True

NUM_ENV_SEEDS: 0
NUM_ENVS: 128
TEST_NUM_ENVS: 10_000
EVAL_STEPS: 100
EVAL_EPISODES: 10  # 32 x (1,000)
EVAL_LOG_PERIOD_ACTOR: 25
EPSILON_ANNEAL_TIME: 5e6
FIXED_EPSILON: 2
STEP_COST: 0

TRAINING_INTERVAL: 5
LEARNING_STARTS: 0
LR: 0.0003

MAX_PRIORITY_WEIGHT: 0.9
IMPORTANCE_SAMPLING_EXPONENT: 0.6

TOTAL_BATCH_SIZE: null
BUFFER_BATCH_SIZE: 64
SAMPLE_LENGTH: 80

USE_BIAS: False
ACTIVATION: 'leaky_relu'
NUM_MLP_LAYERS: 1
MLP_HIDDEN_DIM: 512
NUM_Q_LAYERS: 1
NUM_AUX_LAYERS: 0
AGENT_RNN_DIM: 256




