# WANDB PARAMS
PROJECT: "craftax-multigoal"
#ENV_NAME: "craftax-gen"
#ENV: "craftax-gen"
TOTAL_TIMESTEPS: 2_000_000

OPTIMISTIC_RESET_RATIO: 1  # reset every env?

EVAL_STEPS: 100
EVAL_EPISODES: 10  # 32 x (1,000)
EVAL_LOG_PERIOD_ACTOR: 25
EPSILON_ANNEAL_TIME: 5e5
FIXED_EPSILON: 2
STEP_COST: 0

SIMULATION_LENGTH: 20
TRAINING_INTERVAL: 1
LEARNING_STARTS: 0
MULTIGOAL: True
AUX_COEFF: 0.0
OFFTASK_COEFF: 1.0


MAX_PRIORITY_WEIGHT: 0.0
IMPORTANCE_SAMPLING_EXPONENT: 0.0
USE_BIAS: True
ACTIVATION: 'relu'
NUM_MLP_LAYERS: 1
MLP_HIDDEN_DIM: 512


NUM_SIMULATIONS: 4
NUM_OFFTASK_GOALS: 3 # + 1 more for dyna
NUM_Q_LAYERS: 1
NUM_AUX_LAYERS: 1
AGENT_RNN_DIM: 256
