# WANDB PARAMS
PROJECT: "craftax"
ENV_NAME: "craftax-gen"
ENV: "craftax-gen"
TOTAL_TIMESTEPS: 1_000_000

OPTIMISTIC_RESET_RATIO: 16
FIXED_EPSILON: 0
SIMULATION_LENGTH: 5
SIMULATION_LENGTH: 1
LEARNING_STARTS: 0