# rollouts
"NUM_ENVS": 2
"TOTAL_TIMESTEPS": 50
"NUM_EXTRA_REPLAY": 4
# eval-specific
"EVAL_EPISODES": 1
"EVAL_STEPS": 10


# batches
"BUFFER_SIZE": 100
"LEARNING_STARTS": 10
"TOTAL_BATCH_SIZE": 12
"BUFFER_BATCH_SIZE": 2
"SAMPLE_LENGTH": null
"TOTAL_EXTRA_BATCH_SIZE": null
"EXTRA_BATCH_SIZE": 3
"EXTRA_SAMPLE_LENGTH": null

# logging
"LEARNER_LOG_PERIOD": 1
"GRADIENT_LOG_PERIOD": 1
"LEARNER_EXTRA_LOG_PERIOD": 1
"EVAL_LOG_PERIOD": 1
"MAX_EPISODE_LOG_LEN": 2
"DEBUG": True
"OBSERVER_PERIOD": 10
"OBSERVER_EPISODES": 1


# 
"NUM_SIMULATIONS": 2
"SIMULATION_LENGTH": 3

BATCH_SIZE: 12
TRAINING_INTERVAL: 3
NUM_EPOCHS: 1
NUM_MINIBATCHES: 1

# NEURAL NET PARAMS
"EMBED_HIDDEN_DIM": 8
"NUM_MLP_LAYERS": 0
"NUM_EMBED_LAYERS": 0
"MLP_HIDDEN_DIM": 8
"AGENT_RNN_DIM": 8
"ACTIVATION": 'leaky_relu'
"NUM_Q_LAYERS": 0

"ENV_KWARGS":
  time_limit: 4
